name = "Meridian Performance Plus"
author = "mfcfbro"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2baf44e55f4254810f504e3202ac9dc8d992bff8ac8345e66a9ffb848faf465"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
